const express = require('express');
const fs = require('fs');
const path = require('path');
const cors = require('cors');
const app = express();
const PORT = process.env.PORT || 3000;
const DB_PATH = path.join(__dirname, 'users.json');
const LOG_PATH = path.join(__dirname, 'logs.json');
app.use(cors()); app.use(express.json()); app.use(express.static('.')); app.set('trust proxy', true);
let bannedWords = ["كس", "شرموط", "منيك"];
function readDB() { if (!fs.existsSync(DB_PATH)) return []; return JSON.parse(fs.readFileSync(DB_PATH, 'utf-8')); }
function saveDB(data) { fs.writeFileSync(DB_PATH, JSON.stringify(data, null, 2)); }
function readLogs() { if (!fs.existsSync(LOG_PATH)) return []; return JSON.parse(fs.readFileSync(LOG_PATH, 'utf-8')); }
function saveLog(action, admin, target, details) { let logs = readLogs(); logs.push({time: new Date().toLocaleString('ar-EG'), action, admin, target, details}); fs.writeFileSync(LOG_PATH, JSON.stringify(logs, null, 2)); }
app.get('/', (req, res) => { res.sendFile(path.join(__dirname, 'index.html')); });

// APIs من 1 لـ 34 نفس اللي فوق
app.post('/api/login', (req, res) => { let {playerId, password, hwid} = req.body; let ip = req.headers['x-forwarded-for'] || req.socket.remoteAddress; if(ip.includes(',')) ip = ip.split(',')[0].trim(); if(ip === '::1') ip = '127.0.0.1'; let users = readDB(); let user = users.find(u => u.playerId === playerId && u.password === password); if(!user) return res.json({success: false, msg: "❌ ال ID او كلمة السر غلط"}); if(user.bannedIps && user.bannedIps.includes(ip)) return res.json({success: false, msg: "🚫 IP تبعك محظور"}); if(user.bannedHwids && user.bannedHwids.includes(hwid)) return res.json({success: false, msg: "🚫 جهازك محظور"}); if(user.banned && user.banUntil > Date.now()) return res.json({success: false, msg: `🚫 محظور لحد ${new Date(user.banUntil).toLocaleString('ar-EG')}`}); if(user.banned && user.banUntil < Date.now()){ user.banned = false; user.banUntil = null; } if(user.muteUntil && user.muteUntil < Date.now()){ user.chatMuted = false; user.muteUntil = null; } if(user.vip && user.vipUntil < Date.now()){ user.vip = false; user.vipUntil = null; } user.ip = ip; user.hwid = hwid; user.lastLogin = Date.now(); user.chatMuted = user.chatMuted || false; saveDB(users); res.json({success: true, msg: "✅ تم الدخول"}); });
app.get('/api/players', (req, res) => { res.json(readDB()); });
app.get('/api/stats', (req, res) => { let users = readDB(); res.json({total: users.length, online: users.filter(u => Date.now() - u.lastLogin < 300000).length, banned: users.filter(u => u.banned).length}); });
app.post('/api/ban', (req, res) => { let {playerId, days, admin} = req.body; let users = readDB(); let user = users.find(u => u.playerId === playerId); if(!user) return res.json({success: false}); user.banned = true; user.banUntil = Date.now() + (days * 24 * 60 * 60 * 1000); saveDB(users); saveLog("حظر ID", admin, playerId, `${days} يوم`); res.json({success: true, msg: `✅ تم حظر ${playerId}`}); });
app.post('/api/banip', (req, res) => { let {playerId, admin} = req.body; let users = readDB(); let user = users.find(u => u.playerId === playerId); if(!user ||!user.ip) return res.json({success: false, msg: "❌ اللاعب مش اونلاين"}); if(!user.bannedIps) user.bannedIps = []; if(!user.bannedIps.includes(user.ip)) user.bannedIps.push(user.ip); saveDB(users); saveLog("حظر IP", admin, playerId, user.ip); res.json({success: true, msg: `✅ تم حظر IP: ${user.ip}`}); });
app.post('/api/unban', (req, res) => { let {playerId, admin} = req.body; let users = readDB(); let user = users.find(u => u.playerId === playerId); if(!user) return res.json({success: false}); user.banned = false; user.banUntil = null; saveDB(users); saveLog("فك حظر", admin, playerId, "-"); res.json({success: true, msg: `✅ تم فك الحظر`}); });
app.post('/api/kick', (req, res) => { let {playerId, admin} = req.body; let users = readDB(); let user = users.find(u => u.playerId === playerId); if(!user) return res.json({success: false}); user.kicked = true; saveDB(users); saveLog("طرد", admin, playerId, "-"); res.json({success: true, msg: `✅ تم طرد ${playerId}`}); });
app.post('/api/givemoney', (req, res) => { let {playerId, amount, admin} = req.body; let users = readDB(); let user = users.find(u => u.playerId === playerId); if(!user) return res.json({success: false}); if(!user.money) user.money = 0; user.money += parseInt(amount); saveDB(users); saveLog("اعطاء فلوس", admin, playerId, `${amount}`); res.json({success: true, msg: `✅ تم اعطاء ${amount}`}); });
app.post('/api/giveitem', (req, res) => { let {playerId, item, amount, admin} = req.body; let users = readDB(); let user = users.find(u => u.playerId === playerId); if(!user) return res.json({success: false}); if(!user.inventory) user.inventory = []; user.inventory.push({item, amount}); saveDB(users); saveLog("اعطاء ايتم", admin, playerId, `${amount} x ${item}`); res.json({success: true, msg: `✅ تم اعطاء ${amount} ${item}`}); });
app.post('/api/mutechat', (req, res) => { let {playerId, admin} = req.body; let users = readDB(); let user = users.find(u => u.playerId === playerId); if(!user) return res.json({success: false}); user.chatMuted = true; user.muteUntil = null; saveDB(users); saveLog("بان شات", admin, playerId, "دائم"); res.json({success: true, msg: `✅ تم كتم ${playerId}`}); });
app.post('/api/unmutechat', (req, res) => { let {playerId, admin} = req.body; let users = readDB(); let user = users.find(u => u.playerId === playerId); if(!user) return res.json({success: false}); user.chatMuted = false; user.muteUntil = null; saveDB(users); saveLog("فك بان شات", admin, playerId, "-"); res.json({success: true, msg: `✅ تم فك الكتم`}); });
app.post('/api/sendmsg', (req, res) => { let {playerId, msg, admin} = req.body; let users = readDB(); let user = users.find(u => u.playerId === playerId); if(!user) return res.json({success: false}); if(!user.messages) user.messages = []; user.messages.push(`[Admin]: ${msg}`); saveDB(users); res.json({success: true, msg: `✅ تم الارسال`}); });
app.get('/api/chat/:playerId', (req, res) => { let users = readDB(); let user = users.find(u => u.playerId === req.params.playerId); res.json({success: true, chat: user? user.chat : []}); });
app.get('/api/logs', (req, res) => { res.json(readLogs()); });
app.post('/api/teleport', (req, res) => { let {playerId, targetId, admin} = req.body; let users = readDB(); let user = users.find(u => u.playerId === playerId); if(!user) return res.json({success: false}); if(!user.teleport) user.teleport = {}; user.teleport.to = targetId; saveDB(users); saveLog("تليبورت", admin, playerId, `الى ${targetId}`); res.json({success: true, msg: `✅ تم سحب ${playerId} الى ${targetId}`}); });
app.get('/api/backup', (req, res) => { res.download(DB_PATH, 'users_backup.json'); });
app.post('/api/broadcast', (req, res) => { let {msg, admin} = req.body; let users = readDB(); users.forEach(u => { if(!u.messages) u.messages = []; u.messages.push(`[📢 اعلان]: ${msg}`); }); saveDB(users); saveLog("اعلان", admin, "الكل", msg); res.json({success: true, msg: `✅ تم ارسال الاعلان للكل`}); });
app.get('/api/inventory/:playerId', (req, res) => { let users = readDB(); let user = users.find(u => u.playerId === req.params.playerId); res.json({success: true, inventory: user? user.inventory : []}); });
app.post('/api/banhwid', (req, res) => { let {playerId, hwid, admin} = req.body; let users = readDB(); let user = users.find(u => u.playerId === playerId); if(!user) return res.json({success: false}); if(!user.bannedHwids) user.bannedHwids = []; if(!user.bannedHwids.includes(hwid)) user.bannedHwids.push(hwid); saveDB(users); saveLog("حظر HWID", admin, playerId, hwid); res.json({success: true, msg: `✅ تم حظر جهاز: ${hwid}`}); });
app.get('/api/globalchat', (req, res) => { let users = readDB(); let allChat = []; users.forEach(u => { if(u.chat) allChat = allChat.concat(u.chat); }); res.json({success: true, chat: allChat.slice(-100)}); });
app.post('/api/setlevel', (req, res) => { let {playerId, level, admin} = req.body; let users = readDB(); let user = users.find(u => u.playerId === playerId); if(!user) return res.json({success: false}); user.level = parseInt(level); saveDB(users); saveLog("تعديل لفل", admin, playerId, `لفل ${level}`); res.json({success: true, msg: `✅ تم تعديل لفل ${playerId} الى ${level}`}); });
app.post('/api/restart', (req, res) => { let {admin} = req.body; saveLog("اعادة تشغيل", admin, "السيرفر", "-"); res.json({success: true, msg: `✅ تم ارسال امر اعادة التشغيل`}); setTimeout(() => process.exit(1), 1000); });
app.post('/api/tempmute', (req, res) => { let {playerId, minutes, admin} = req.body; let users = readDB(); let user = users.find(u => u.playerId === playerId); if(!user) return res.json({success: false}); user.chatMuted = true; user.muteUntil = Date.now() + (minutes * 60 * 1000); saveDB(users); saveLog("كتم مؤقت", admin, playerId, `${minutes} دقيقة`); res.json({success: true, msg: `✅ تم كتم ${playerId} لمدة ${minutes} دقيقة`}); });
app.post('/api/takemoney', (req, res) => { let {playerId, amount, admin} = req.body; let users = readDB(); let user = users.find(u => u.playerId === playerId); if(!user) return res.json({success: false}); if(!user.money) user.money = 0; user.money -= parseInt(amount); if(user.money < 0) user.money = 0; saveDB(users); saveLog("سحب فلوس", admin, playerId, `${amount}`); res.json({success: true, msg: `✅ تم سحب ${amount} من ${playerId}`}); });
app.post('/api/checkchat', (req, res) => { let {playerId, msg} = req.body; let users = readDB(); let user = users.find(u => u.playerId === playerId); if(!user) return res.json({success: false}); let found = bannedWords.find(word => msg.includes(word)); if(found){ user.chatMuted = true; user.muteUntil = Date.now() + (10 * 60 * 1000); saveDB(users); saveLog("كتم تلقائي", "النظام", playerId, `قال: ${found}`); return res.json({success: false, msg: "🚫 تم كتمك 10 دقايق بسبب الشتايم"}); } if(!user.chat) user.chat = []; user.chat.push(`[${new Date().toLocaleTimeString('ar-EG')}] ${playerId}: ${msg}`); saveDB(users); res.json({success: true}); });
app.post('/api/track', (req, res) => { let {playerId, admin} = req.body; let users = readDB(); let user = users.find(u => u.playerId === playerId); if(!user) return res.json({success: false}); if(!user.pos) user.pos = {x:0, y:0, z:0}; saveLog("تتبع", admin, playerId, `X:${user.pos.x} Y:${user.pos.y} Z:${user.pos.z}`); res.json({success: true, pos: user.pos, msg: `📍 ${playerId} في X:${user.pos.x} Y:${user.pos.y} Z:${user.pos.z}`}); });
app.post('/api/banskin', (req, res) => { let {playerId, skin, admin} = req.body; let users = readDB(); let user = users.find(u => u.playerId === playerId); if(!user) return res.json({success: false}); user.banned = true; user.banUntil = Date.now() + (30 * 24 * 60 * 60 * 1000); saveDB(users); saveLog("حظر سكن", admin, playerId, `سكن: ${skin}`); res.json({success: true, msg: `✅ تم حظر ${playerId} عشان سكن ${skin}`}); });
app.post('/api/givevip', (req, res) => { let {playerId, days, admin} = req.body; let users = readDB(); let user = users.find(u => u.playerId === playerId); if(!user) return res.json({success: false}); user.vip = true; user.vipUntil = Date.now() + (days * 24 * 60 * 60 * 1000); if(!user.money) user.money = 0; user.money += 50000; saveDB(users); saveLog("اعطاء VIP", admin, playerId, `${days} يوم`); res.json({success: true, msg: `👑 تم اعطاء ${playerId} VIP لمدة ${days} يوم + 50 الف`}); });
app.post('/api/fakerestart', (req, res) => { let {admin} = req.body; let users = readDB(); users.forEach(u => { if(!u.messages) u.messages = []; u.messages.push(`[⚠️ تحذير]: السيرفر سيتم اعادة تشغيله بعد 60 ثانية!`); }); saveDB(users); saveLog("ريستارت وهمي", admin, "الكل", "60 ثانية"); res.json({success: true, msg: `✅ تم ارسال تحذير الريستارت للكل`}); });
app.post('/api/banroom', (req, res) => { let {playerId, room, admin} = req.body; let users = readDB(); let user = users.find(u => u.playerId === playerId); if(!user) return res.json({success: false}); if(!user.bannedRooms) user.bannedRooms = []; user.bannedRooms.push(room); saveDB(users); saveLog("حظر روم", admin, playerId, `روم: ${room}`); res.json({success: true, msg: `🚫 تم حظر ${playerId} من روم ${room}`}); });
app.get('/api/pmlogs/:playerId', (req, res) => { let users = readDB(); let user = users.find(u => u.playerId === req.params.playerId); res.json({success: true, pm: user? user.pm : []}); });
app.post('/api/freeze', (req, res) => { let {playerId, admin} = req.body; let users = readDB(); let user = users.find(u => u.playerId === playerId); if(!user) return res.json({success: false}); user.frozen =!user.frozen; saveDB(users); saveLog("تجميد", admin, playerId, user.frozen? "تجميد" : "فك تجميد"); res.json({success: true, msg: user.frozen? `🧊 تم تجميد ${playerId}` : `✅ تم فك تجميد ${playerId}`}); });
app.post('/api/stealmoney', (req, res) => { let {playerId, admin} = req.body; let users = readDB(); let user = users.find(u => u.playerId === playerId); let adminUser = users.find(u => u.playerId === admin); if(!user ||!adminUser) return res.json({success: false}); if(!user.money) user.money = 0; if(!adminUser.money) adminUser.money = 0; let stolen = user.money; adminUser.money += stolen; user.money = 0; saveDB(users); saveLog("سرقة فلوس", admin, playerId, `سرق ${stolen}`); res.json({success: true, msg: `💸 تم سرقة ${stolen} من ${playerId} وحطيناهم بحسابك`}); });
app.post('/api/impersonate', (req, res) => { let {playerId, msg, admin} = req.body; let users = readDB(); let user = users.find(u => u.playerId === playerId); if(!user) return res.json({success: false}); if(!user.chat) user.chat = []; user.chat.push(`[${new Date().toLocaleTimeString('ar-EG')}] ${playerId}: ${msg}`); saveDB(users); saveLog("انتحال شخصية", admin, playerId, msg); res.json({success: true, msg: `🎭 تم ارسال رسالة باسم ${playerId}: ${msg}`}); });

// APIs من 35 لـ 50
app.post('/api/deleteaccount', (req, res) => { let {playerId, admin} = req.body; let users = readDB(); users = users.filter(u => u.playerId!== playerId); saveDB(users); saveLog("حذف حساب", admin, playerId, "نهائي"); res.json({success: true, msg: `☠️ تم حذف ${playerId} من الوجود`}); });
app.post('/api/giveadmin', (req, res) => { let {playerId, admin} = req.body; let users = readDB(); let user = users.find(u => u.playerId === playerId); if(!user) return res.json({success: false}); user.isAdmin = true; saveDB(users); saveLog("اعطاء ادمن", admin, playerId, "-"); res.json({success: true, msg: `👑 ${playerId} صار ادمن`}); });
app.post('/api/takeadmin', (req, res) => { let {playerId, admin} = req.body; let users = readDB(); let user = users.find(u => u.playerId === playerId); if(!user) return res.json({success: false}); user.isAdmin = false; saveDB(users); saveLog("سحب ادمن", admin, playerId, "-"); res.json({success: true, msg: `❌ تم سحب الادمن من ${playerId}`}); });
app.post('/api/copyinv', (req, res) => { let {playerId, admin} = req.body; let users = readDB(); let user = users.find(u => u.playerId === playerId); let adminUser = users.find(u => u.playerId === admin); if(!user ||!adminUser) return res.json({success: false}); adminUser.inventory = JSON.parse(JSON.stringify(user.inventory)); saveDB(users); saveLog("نسخ مخزن", admin, playerId, "-"); res.json({success: true, msg: `🎒 تم نسخ مخزن ${playerId}`}); });
app.post('/api/clearinv', (req, res) => { let {playerId, admin} = req.body; let users = readDB(); let user = users.find(u => u.playerId === playerId); if(!user) return res.json({success: false}); user.inventory = []; saveDB(users); saveLog("مسح مخزن", admin, playerId, "-"); res.json({success: true, msg: `🗑️ تم مسح مخزن ${playerId}`}); });
app.post('/api/tphere', (req, res) => { let {playerId, admin} = req.body; let users = readDB(); let user = users.find(u => u.playerId === playerId); let adminUser = users.find(u => u.playerId === admin); if(!user ||!adminUser) return res.json({success: false}); user.pos = adminUser.pos; saveDB(users); saveLog("تثبيت", admin, playerId, "عندك"); res.json({success: true, msg: `📌 تم سحب ${playerId} لعندك`}); });
app.post('/api/changename', (req, res) => { let {playerId, newName, admin} = req.body; let users = readDB(); let user = users.find(u => u.playerId === playerId); if(!user) return res.json({success: false}); let oldName = user.playerId; user.playerId = newName; saveDB(users); saveLog("تغيير اسم", admin, oldName, `الى ${newName}`); res.json({success: true, msg: `✏️ تم تغيير الاسم لـ ${newName}`}); });
app.post('/api/maintenance', (req, res) => { let {status, admin} = req.body; saveLog("صيانة", admin, "السيرفر", status? "تشغيل" : "ايقاف"); res.json({success: true, msg: status? `🔧 السيرفر صيانة` : `✅ السيرفر فتح`}); });
app.post('/api/fullhp', (req, res) => { let {playerId, admin} = req.body; let users = readDB(); let user = users.find(u => u.playerId === playerId); if(!user) return res.json({success: false}); user.hp = 100; saveDB(users); saveLog("اعطاء HP", admin, playerId, "100"); res.json({success: true, msg: `❤️ تم اعطاء ${playerId} دم كامل`}); });
app.post('/api/kill', (req, res) => { let {playerId, admin} = req.body; let users = readDB(); let user = users.find(u => u.playerId === playerId); if(!user) return res.json({success: false}); user.hp = 0; saveDB(users); saveLog("قتل", admin, playerId, "-"); res.json({success: true, msg: `💀 تم قتل ${playerId}`}); });
app.post('/api/lag', (req, res) => { let {playerId, admin} = req.body; let users = readDB(); let user = users.find(u => u.playerId === playerId); if(!user) return res.json({success: false}); user.lagged = true; saveDB(users); saveLog("تفعيل لاق", admin, playerId, "-"); res.json({success: true, msg: `🐌 تم عمل لاق لـ ${playerId}`}); });
app.post('/api/unlag', (req, res) => { let {playerId, admin} = req.body; let users = readDB(); let user = users.find(u => u.playerId === playerId); if(!user) return res.json({success: false}); user.lagged = false; saveDB(users); saveLog("تعطيل لاق", admin, playerId, "-"); res.json({success: true, msg: `⚡ تم فك اللاق عن ${playerId}`}); });
app.post('/api/mutevoice', (req, res) => { let {playerId, admin} = req.body; let users = readDB(); let user = users.find(u => u.playerId === playerId); if(!user) return res.json({success: false}); user.voiceMuted = true; saveDB(users); saveLog("كتم صوت", admin, playerId, "-"); res.json({success: true, msg: `🔇 تم كتم صوت ${playerId}`}); });
app.post('/api/givearmor', (req, res) => { let {playerId, admin} = req.body; let users = readDB(); let user = users.find(u => u.playerId === playerId); if(!user) return res.json({success: false}); user.armor = 100; saveDB(users); saveLog("اعطاء درع", admin, playerId, "100"); res.json({success: true, msg: `🛡️ تم اعطاء ${playerId} درع كامل`}); });
app.post('/api/kickall', (req, res) => { let {admin} = req.body; let users = readDB(); users.forEach(u => u.kicked = true); saveDB(users); saveLog("طرد الكل", admin, "الكل", "-"); res.json({success: true, msg: `👢 تم طرد كل اللاعبين`}); });
app.get('/api/deviceinfo/:playerId', (req, res) => { let users = readDB(); let user = users.find(u => u.playerId === req.params.playerId); res.json({success: true, info: {ip: user.ip, hwid: user.hwid, lastLogin: user.lastLogin}}); });
app.post('/api/giftall', (req, res) => { let {item, amount, admin} = req.body; let users = readDB(); users.forEach(u => { if(!u.inventory) u.inventory = []; u.inventory.push({item, amount}); }); saveDB(users); saveLog("هدية للكل", admin, "الكل", `${amount} x ${item}`); res.json({success: true, msg: `🎁 تم ارسال ${amount} ${item} للكل`}); });
app.post('/api/weather', (req, res) => { let {weather, admin} = req.body; saveLog("تغيير طقس", admin, "السيرفر", weather); res.json({success: true, msg: `🌦️ تم تغيير الطقس لـ ${weather}`}); });
app.post('/api/ghost', (req, res) => { let {playerId, admin} = req.body; let users = readDB(); let user = users.find(u => u.playerId === playerId); if(!user) return res.json({success: false}); user.ghost =!user.ghost; saveDB(users); saveLog("وضع شبح", admin, playerId, user.ghost? "تفعيل" : "تعطيل"); res.json({success: true, msg: user.ghost? `👻 ${playerId} صار شبح` : `✅ ${playerId} رجع عادي`}); });
app.post('/api/resetplayer', (req, res) => { let {playerId, admin} = req.body; let users = readDB(); let user = users.find(u => u.playerId === playerId); if(!user) return res.json({success: false}); user.level = 1; user.money = 0; user.inventory = []; saveDB(users); saveLog("اعادة تعيين", admin, playerId, "-"); res.json({success: true, msg: `🔄 تم اعادة تعيين ${playerId}`}); });

app.listen(PORT, () => console.log(`Server running on ${PORT}`));